import { readFileSync, existsSync } from "node:fs";
import process from "node:process";
import console from "node:console";
import ts from "typescript";
const result = ts.parseConfigFileTextToJson("wrangler.jsonc", readFileSync("wrangler.jsonc", "utf8"));
if (result.error) throw new Error("Invalid wrangler.jsonc");
const config = result.config;
const worker = readFileSync(config.main, "utf8");
const docs = readFileSync("docs/deployment.md", "utf8");
let failures = 0;
function check(ok, label) {
  console.log(`${ok ? "✓" : "✗"} ${label}`);
  if (!ok) failures++;
}
check(
  config.d1_databases?.some((x) => x.binding === "DB"),
  "D1 configured",
);
check(
  config.r2_buckets?.some((x) => x.binding === "ATTACHMENTS"),
  "Private R2 binding configured (public access must be checked in dashboard)",
);
for (const binding of ["INBOUND_MAIL_QUEUE", "OUTBOUND_MAIL_QUEUE", "MAINTENANCE_QUEUE"]) {
  const producer = config.queues?.producers?.find((x) => x.binding === binding);
  const consumer = config.queues?.consumers?.find((x) => x.queue === producer?.queue);
  check(
    producer && consumer?.max_batch_size === 1 && consumer?.dead_letter_queue,
    `${binding}: producer, bounded consumer, and dead-letter queue configured`,
  );
}
// Native Cloudflare email is opt-in and stays commented out in the shipped
// config, so its blocks are only validated once someone enables them.
const emailBinding = config.send_email?.find((x) => x.name === "EMAIL");
const emailEventsConsumer = config.queues?.consumers?.find((x) => x.queue === "resolvehq-email-events");
if (emailBinding || emailEventsConsumer) {
  check(Boolean(emailBinding), "send_email binding named EMAIL configured");
  check(
    Boolean(emailEventsConsumer?.dead_letter_queue) &&
      config.queues?.consumers?.some((x) => x.queue === emailEventsConsumer?.dead_letter_queue),
    "Delivery-event consumer has a declared dead-letter queue",
  );
  check(
    docs.includes("queues subscription create"),
    "Delivery-event subscription step documented (it cannot be declared in wrangler.jsonc)",
  );
} else {
  console.log(
    "\u2139 Native Cloudflare email (send_email binding and resolvehq-email-events consumer) is commented out; Resend remains the sending provider.",
  );
}
check(
  !config.ai || config.ai.binding === "AI",
  config.ai ? "Workers AI binding configured (preferred over OPENAI_API_KEY)" : "Workers AI binding not configured (optional; uncomment `ai` in wrangler.jsonc to enable, or set OPENAI_API_KEY)",
);
check(config.triggers?.crons?.length && /scheduled\s*\(/.test(worker), "Cron configured with handler");
check(/email\s*\(/.test(worker), "Email handler configured (Email Routing rule requires dashboard setup)");
check(config.main === "worker.ts", "Worker entry point is worker.ts");
// `assets.directory` is deliberately absent: @cloudflare/vite-plugin writes it into the
// generated dist/<worker>/wrangler.json at build time.
check(
  config.assets?.binding === "ASSETS" &&
    config.assets?.run_worker_first?.includes("/api/*") &&
    !config.assets?.directory,
  "Static assets and API routing configured (directory populated by the Vite plugin)",
);
check(
  config.ratelimits?.some((x) => x.name === "AUTH_RATE_LIMIT") &&
    config.ratelimits?.some((x) => x.name === "WRITE_RATE_LIMIT"),
  "Authentication and write rate limits configured",
);
check(
  config.secrets?.required?.includes("SESSION_PEPPER") &&
    docs.includes("SESSION_PEPPER") &&
    docs.includes("RESEND_API_KEY"),
  "Required secrets declared and documented",
);
check(
  config.observability?.logs?.invocation_logs === false,
  "Automatic invocation logs disabled to protect token-bearing URLs",
);
console.log("⚠ Authentication hashing must be benchmarked after deployment; elapsed timers do not measure CPU.");
console.log(
  "⚠ Local configuration only: account plan, resource provisioning, secrets, R2 activation, Email Routing, and usage quotas are not verified.",
);
const builtAssets = config.assets?.directory ?? "dist/client";
console.log(
  `ℹ Assets ${existsSync(builtAssets) ? "present" : "will be generated by npm run build"} in ${builtAssets}. No Cloudflare account calls made.`,
);
process.exitCode = failures ? 1 : 0;
