import { readFileSync, existsSync } from "node:fs";
import process from "node:process";
import console from "node:console";
import ts from "typescript";
const result = ts.parseConfigFileTextToJson("wrangler.jsonc", readFileSync("wrangler.jsonc", "utf8"));
if (result.error) throw new Error("Invalid wrangler.jsonc");
const config = result.config;
const worker = readFileSync(config.main, "utf8");
const docs = readFileSync("docs/deployment.md", "utf8");
let failures = 0;
function check(ok, label) {
  console.log(`${ok ? "✓" : "✗"} ${label}`);
  if (!ok) failures++;
}
check(
  config.d1_databases?.some((x) => x.binding === "DB"),
  "D1 configured",
);
check(
  config.r2_buckets?.some((x) => x.binding === "ATTACHMENTS"),
  "Private R2 binding configured (public access must be checked in dashboard)",
);
for (const binding of ["INBOUND_MAIL_QUEUE", "OUTBOUND_MAIL_QUEUE", "MAINTENANCE_QUEUE"]) {
  const producer = config.queues?.producers?.find((x) => x.binding === binding);
  const consumer = config.queues?.consumers?.find((x) => x.queue === producer?.queue);
  check(
    producer && consumer?.max_batch_size === 1 && consumer?.dead_letter_queue,
    `${binding}: producer, bounded consumer, and dead-letter queue configured`,
  );
}
check(config.triggers?.crons?.length && /scheduled\s*\(/.test(worker), "Cron configured with handler");
check(/email\s*\(/.test(worker), "Email handler configured (Email Routing rule requires dashboard setup)");
check(
  config.assets?.binding === "ASSETS" && config.assets?.run_worker_first?.includes("/api/*"),
  "Static assets and API routing configured",
);
check(
  config.ratelimits?.some((x) => x.name === "AUTH_RATE_LIMIT") &&
    config.ratelimits?.some((x) => x.name === "WRITE_RATE_LIMIT"),
  "Authentication and write rate limits configured",
);
check(
  config.secrets?.required?.includes("SESSION_PEPPER") &&
    docs.includes("SESSION_PEPPER") &&
    docs.includes("RESEND_API_KEY"),
  "Required secrets declared and documented",
);
check(
  config.observability?.logs?.invocation_logs === false,
  "Automatic invocation logs disabled to protect token-bearing URLs",
);
console.log("⚠ Authentication hashing must be benchmarked after deployment; elapsed timers do not measure CPU.");
console.log(
  "⚠ Local configuration only: account plan, resource provisioning, secrets, R2 activation, Email Routing, and usage quotas are not verified.",
);
console.log(
  `ℹ Assets ${existsSync(config.assets.directory) ? "present" : "will be generated by npm run build"}. No Cloudflare account calls made.`,
);
process.exitCode = failures ? 1 : 0;
