import { useCallback, useEffect, useState, type FormEvent } from "react";
import { Building2, Mail, Plus, Search, TicketCheck, X } from "lucide-react";
import { Link } from "react-router-dom";
import { api } from "@/web/lib/api";
import { Button, Input } from "@/web/components/ui";

interface Customer { id: string; name: string; email: string; company: string | null; phone: string | null; ticketCount: number; lastContactedAt: string | null }
interface CustomerDetail { customer: Customer & { notes: string | null; createdAt: string }; tickets: Array<{ id: string; number: number; subject: string; status: string; priority: string; updatedAt: string }> }

export function CustomersPage() {
  const [customers, setCustomers] = useState<Customer[]>([]); const [query, setQuery] = useState(""); const [creating, setCreating] = useState(false); const [error, setError] = useState(""); const [detail, setDetail] = useState<CustomerDetail | null>(null);
  const load = useCallback(async (value = query) => { const result = await api<{ customers: Customer[] }>(`/customers${value ? `?q=${encodeURIComponent(value)}` : ""}`); setCustomers(result.customers); }, [query]);
  useEffect(() => { const timeout = window.setTimeout(() => void load(query), 200); return () => window.clearTimeout(timeout); }, [load, query]);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); const form = event.currentTarget; try { await api("/customers", { method: "POST", body: JSON.stringify(Object.fromEntries(new FormData(form))) }); form.reset(); setCreating(false); await load(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not create customer."); } }
  async function openCustomer(id: string) { try { setDetail(await api<CustomerDetail>(`/customers/${id}`)); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not open customer history."); } }
  async function saveNotes(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!detail) return; const notes = String(new FormData(event.currentTarget).get("notes")); await api(`/customers/${detail.customer.id}`, { method: "PATCH", body: JSON.stringify({ notes }) }); setDetail({ ...detail, customer: { ...detail.customer, notes } }); }
  return <div className="standard-page"><header className="page-header"><div><h1>Customers</h1><p>People, companies, and the full history behind each conversation.</p></div><Button onClick={() => setCreating((value) => !value)}><Plus size={16} />Add customer</Button></header>
    {creating && <form className="inline-create" onSubmit={create}><div><label>Name<Input name="name" required /></label><label>Email<Input name="email" type="email" required /></label><label>Company<Input name="company" /></label></div>{error && <p className="form-error">{error}</p>}<footer><Button type="button" variant="ghost" onClick={() => setCreating(false)}>Cancel</Button><Button type="submit">Create customer</Button></footer></form>}
    <label className="page-search"><Search size={16} /><input placeholder="Search customers" value={query} onChange={(event) => setQuery(event.target.value)} /></label>
    <div className="customer-ledger"><div className="customer-ledger-head"><span>Customer</span><span>Company</span><span>Last contacted</span><span>Tickets</span></div>{customers.map((customer) => <button type="button" className="customer-row" key={customer.id} onClick={() => void openCustomer(customer.id)}><div className="customer-identity"><span>{customer.name.slice(0, 1)}</span><div><strong>{customer.name}</strong><small><Mail size={12} />{customer.email}</small></div></div><div>{customer.company ? <><Building2 size={14} />{customer.company}</> : <em>Independent</em>}</div><time>{customer.lastContactedAt ? new Date(customer.lastContactedAt).toLocaleDateString() : "No contact yet"}</time><div><TicketCheck size={14} />{customer.ticketCount}</div></button>)}</div>
    {detail && <section className="customer-detail" aria-label={`${detail.customer.name} history`}><header><div><h2>{detail.customer.name}</h2><p>{detail.customer.email}{detail.customer.company ? ` · ${detail.customer.company}` : ""}</p></div><button type="button" aria-label="Close customer details" onClick={() => setDetail(null)}><X size={18} /></button></header><div className="customer-summary"><span><strong>{detail.tickets.filter((ticket) => !["resolved", "closed"].includes(ticket.status)).length}</strong>Open</span><span><strong>{detail.tickets.filter((ticket) => ["resolved", "closed"].includes(ticket.status)).length}</strong>Resolved</span><span><strong>{detail.tickets.length}</strong>Total</span></div><form onSubmit={saveNotes}><label>Team notes<textarea name="notes" defaultValue={detail.customer.notes ?? ""} rows={3} placeholder="Context that helps the support team…" /></label><Button type="submit" size="small">Save notes</Button></form><div className="customer-history"><h3>Conversation history</h3>{detail.tickets.length ? detail.tickets.map((ticket) => <Link key={ticket.id} to={`/inbox/${ticket.id}`}><span className={`status-pin status-${ticket.status}`} /><div><strong>{ticket.subject}</strong><small>#{ticket.number} · {ticket.status.replace("_", " ")}</small></div><time>{new Date(ticket.updatedAt).toLocaleDateString()}</time></Link>) : <p>No conversations yet.</p>}</div></section>}
  </div>;
}
